import re
p = re.compile('ca{2}t')
m = p.match('ct')
print(m)
m = p.match('cat')
print(m)
m = p.match('caat')
print(m)
m = p.match('caaaat')
print(m)

p = re.compile('ca{2,5}t')
m = p.match('ct')
print(m)
m = p.match('caat')
print(m)
m = p.match('caaaaat')
print(m)
m = p.match('caaaaaaaat')
print(m)

p = re.compile('ca{2,}t')
m = p.match('ct')
print(m)
m = p.match('caat')
print(m)
m = p.match('caaaaat')
print(m)
m = p.match('caaaaaaaat')
print(m)


p = re.compile('ca{,5}t')
m = p.match('ct')
print(m)
m = p.match('caat')
print(m)
m = p.match('caaaaat')
print(m)
m = p.match('caaaaaaaat')
print(m)

