import re
p = re.compile(r'\Aclass')
m = p.search('class is forever')
print(m)
p = re.compile(r'class\Z')
m = p.search('class is forever class')
print(m)
p = re.compile(r'\bclass')
m = p.search('class is forever class')
print(m)
# p = re.compile(r'class\b')
# m = p.search('is forever beclass')
# print(m)
# p = re.compile(r'class\B')
# m = p.search('is forever beclass')
# print(m)
# p = re.compile(r'class\B')
# m = p.search('abclassde')
# print(m)
# p = re.compile(r'\Bclass')
# m = p.search('abclassde')
# print(m)
