import re
p = re.compile('[a-z]+')
m = p.match('ppytaaahon')
print(m)
p = re.compile('[a-z]')
m = p.match('ppytaaahon')
print(m)
p = re.compile('^[a-z]')
m = p.match('CaB')
print(m)
p = re.compile('[^a-z]')
m = p.match('CaB')
print(m)
p = re.compile('^[a-z]')
m = p.search('aCaB')
print(m)
p = re.compile('a')
m = p.finditer('ACaBa')
print(m)
for i in m:
    print(i)

